# run on container environment
sudo: false

language: php

notifications:
    on_success: change
    on_failure: always

php:
    - 8.0
    - 7.4
    - 7.1

install:
    - composer install --dev --ignore-platform-reqs

before_script:
    - phpenv config-rm xdebug.ini

script:
    - ./vendor/bin/phpunit -v
