language: "php"
os:
  - "linux"
# 18.04 Bionic: PHP 7.1 - 8.0
dist: "bionic"

notifications:
    on_success: change
    on_failure: always

php:
    - "7.4"
    - "7.1"

jobs:
  include:
    - php: "8.0"
      install: composer update --dev --ignore-platform-reqs

before_install: phpenv config-rm xdebug.ini

install: composer update --dev

script: vendor/bin/phpunit -v
